language: csharp

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8

sudo: required

mono: none

dotnet: 3.1

branches:
  only:
  - master

script:
  - ./build.sh --verbosity diagnostic

cache:
    directories:
    - ".packages"
    - "tools/Addins"
    - "tools/gitreleasemanager"
    - "tools/GitVersion.CommandLine"

matrix:
  include:
    - os: linux
      # Ref: https://docs.travis-ci.com/user/reference/xenial
      dist: xenial
    - os: osx
      # Ref: https://docs.travis-ci.com/user/reference/osx
      dotnet: 3.1.100
      osx_image: xcode10.1