version: 1.0.{build}
skip_tags: true
branches:
  only:
    - master
configuration: Debug
environment:
  COVERALLS_REPO_TOKEN:
    secure: nBorIHYuu2rVs0/FKpffgywOvnxA3+E1fkstRpplRxRB261VPFiP+xX7GmR5tPqW
before_build:
  - dotnet restore
  - nuget install -Verbosity quiet opencover -Version 4.6.519 -OutputDirectory tools
  - nuget install -Verbosity quiet coveralls.net -Version 0.7.0 -OutputDirectory tools
build_script:
  - dotnet build -c Debug /p:DebugType=full
test_script:
  - ps: .\tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\script\tests.bat" -searchdirs:".\test\Piranha.Tests\bin\Debug\netcoreapp1.1;.\test\Piranha.AttributeBuilder.Tests\bin\Debug\netcoreapp1.1;.\test\Piranha.ImageSharp.Tests\bin\Debug\netcoreapp1.1" -oldstyle -output:coverage.xml -skipautoprops -returntargetcode -filter:"+[Piranha*]* -[*Tests]*" -excludebyattribute:"Piranha.NoCoverageAttribute"
  - ps: .\tools\coveralls.net.0.7.0\tools\csmacnz.coveralls.exe --opencover -i coverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor
