on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish NuGet Packages
    steps:

    # Checkout
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup .NET Core
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NugetAuthToken}}

    # Setup Node.js
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Install NPM packages and run gulp
    - name: NPM Install and Gulp
      run: |
        cd core/Piranha.Manager
        npm install
        gulp

    # Build and pack
    - name: Build solution and generate NuGet package
      run: ./pack.sh

    # Install SignClient
    - name: Install SignClient
      run: dotnet tool install --tool-path . SignClient

    # Sign packages
    - name: Sign packages
      run: ./SignClient "SIGN" --input "artifacts/*.nupkg" --config "sign.json" --user "${{secrets.SignClientUser}}" --secret "${{secrets.SignClientSecret}}" --name "Piranha" --description "Piranha" --descriptionUrl "https://github.com/piranhacms/piranha.core"

    # Sign symbol packages
    - name: Sign symbol packages
      run: ./SignClient "SIGN" --input "artifacts/*.snupkg" --config "sign.json" --user "${{secrets.SignClientUser}}" --secret "${{secrets.SignClientSecret}}" --name "Piranha" --description "Piranha" --descriptionUrl "https://github.com/piranhacms/piranha.core"

    # Push to NuGet
    - name: Push generated package to GitHub registry
      run: dotnet nuget push '**/Piranha*.nupkg' --skip-duplicate -k ${{ secrets.NugetAuthToken }}
